FROM python:3 as Build

WORKDIR /var/www/

ADD . /var/www/

RUN pip3 install pipenv
RUN pipenv lock --requirements > requirements.txt
RUN pip install uvicorn
RUN pip install -r requirements.txt

CMD ["uvicorn --host 0.0.0.0 --port 5000 'manage:productionApp'"]
