version: "3.5"
services:
  tdctl_api:
    image: ghcr.io/td-org-uit-no/tdctl-api/tdctl-api:latest
    build:
      context: ../
        # dockerfile: .docker/dockerfile.api.production
    environment:
      FLASK_APP_ENV: production
      DB_HOSTNAME: mongodb
      DB_PORT: 27017
      SECRET_KEY: thisisverysecret
    networks:
      - frontend
      - backend

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: tdctl
    networks:
      - backend

  nginx:
    build:
      context: ../
      dockerfile: .docker/dockerfile.nginx
    image: nginx:latest
    ports:
      - "5000:80"
    depends_on:
      - tdctl_api
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
