FROM python:3.8 as Build

WORKDIR /var/www/

ADD . /var/www/

RUN pip3 install pipenv
RUN pipenv requirements > requirements.txt
RUN pip install -r requirements.txt
CMD ["uvicorn", "manage:app", "--host", "0.0.0.0", "--port", "5000"]
