name: Build and push docker image

on:
  push:
    branches:
      - feature/docker_upgrade
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          push: true
          file: .docker/dockerfile.api.production
          tags: ghcr.io/${{ github.repository }}/tdctl-api:latest
