name: Build and push docker image

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: td-org-uit-no
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: td-org-uit-no/tdctl-api/tdctl-api
          registry: docker.pkg.github.com
          dockerfile: .docker/dockerfile.api.production
          tag_with_sha: true
          tag_with_ref: true
