name: Deploy on prod.td.org.uit.no

# Ignore error below
on:
  workflow_run:
    workflows: ["Build and push docker image"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server and launching update script
        uses: appleboy/ssh-action@master
        with:
          host: prod.td.org.uit.no
          username: ${{ secrets.PROD_SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: ./pull-latest-api.sh
