name: Backend tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  TEST_DB_HOSTNAME: localhost
  TEST_DB_PORT: 27017

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0

      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install pipenv
        run: pip install pipenv

      - name: Run tests
        run: |
          pipenv sync
          pipenv run pytest
